MKDIR = mkdir
REMOVE = rm -r
BIN = bin

all:
	$(MKDIR) $(BIN)
	gcc -o bin/tarea3 tarea3.c
	gcc -o bin/ejercicio2 ejercicio2.c
	gcc -o bin/ejercicio3 ejercicio3.c
	gcc -o bin/ejercicio4 ejercicio4.c

clean:
	$(REMOVE) $(BIN)

