MKDIR = mkdir
REMOVE = rm -r
BIN = bin

all:
	$(MKDIR) $(BIN)
	gcc -o bin/tarea9 tarea9.c
	gcc -o bin/tarea10 tarea10.c
	gcc -o bin/envioSignal envioSignal.c
	gcc -o bin/reciboSignal reciboSignal.c
	gcc -o bin/contador contador.c
	gcc -o bin/tarea11 tarea11.c
	gcc -o bin/ejercicio3 ejercicio3.c
	gcc -o bin/tarea12 tarea12.c

clean:
	$(REMOVE) $(BIN)

